name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Name:
    description: The name of the module to test. The name of the repository is used if not specified.
    required: false
  Path:
    description: The path to the code to test.
    required: true
  TestType:
    description: The type of tests to run. Can be either 'Module' or 'SourceCode'.
    required: true
  TestsPath:
    description: The path to the tests to run.
    required: false
    default: tests
  StackTraceVerbosity:
    description: "Verbosity level of the stack trace. Allowed values: 'None', 'FirstLine', 'Filtered', 'Full'."
    required: false
    default: 'Filtered'
  Verbosity:
    description: "Verbosity level of the test output. Allowed values: 'None', 'Normal', 'Detailed', 'Diagnostic'."
    required: false
    default: 'Detailed'

outputs:
  passed:
    description: If the tests passed.
    value: ${{ steps.test.outputs.passed }}

runs:
  using: composite
  steps:
    - name: Run Test-PSModule
      uses: PSModule/GitHub-Script@v1

    - name: Run Test-PSModule
      shell: pwsh
      id: test
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_TestType: ${{ inputs.TestType }}
        GITHUB_ACTION_INPUT_TestsPath: ${{ inputs.TestsPath }}
        GITHUB_ACTION_INPUT_StackTraceVerbosity: ${{ inputs.StackTraceVerbosity }}
        GITHUB_ACTION_INPUT_Verbosity: ${{ inputs.Verbosity }}
      run: |
        # Test-PSModule
        $passed = . "${{ github.action_path }}\scripts\main.ps1" -Verbose
        "passed=$passed" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

        Write-Host "Passed: [$passed]"

        if (-not $passed) {
          exit 1
        }

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ inputs.TestType == 'Module' && (success() || failure()) }}
      with:
        name: ${{ runner.os }}-${{ inputs.Shell }}-Test-Report
        path: ${{ github.workspace }}/outputs/Test-Report.xml

    - name: Upload code coverage report
      uses: actions/upload-artifact@v4
      if: ${{ inputs.TestType == 'Module' && (success() || failure()) }}
      with:
        name: ${{ runner.os }}-${{ inputs.Shell }}-CodeCoverage-Report
        path: ${{ github.workspace }}/outputs/CodeCoverage-Report.xml
