name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Name:
    description: The name of the module to test. The name of the repository is used if not specified.
    required: false
  Path:
    description: The path to the module to test.
    required: true
  TestType:
    description: The type of tests to run.
    required: true
  Shell:
    description: The shell to use for running the tests.
    required: false
    default: pwsh

runs:
  using: composite
  steps:
    - name: Run Test-PSModule
      shell: ${{ inputs.Shell }}
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_TestType: ${{ inputs.TestType }}
      run: |
        # Test-PSModule
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ inputs.TestType == 'Module' }}
      with:
        name: ${{ inputs.Shell }}-${{ runner.os }}-Test-Report
        path: outputs\Test-Report.xml

    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      if: ${{ inputs.TestType == 'Module' }}
      with:
        name: ${{ inputs.Shell }}-${{ runner.os }}-CodeCoverage-Report
        path: outputs\CodeCoverage-Report.xml
