name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Name:
    description: The name of the module to test. The name of the repository is used if not specified.
    required: false
  Path:
    description: The path to the repo.
    required: true
    default: ${{ github.workspace }}
  Settings:
    description: The type of tests to run. Can be either 'Module' or 'SourceCode'.
    required: true
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Get test paths
      uses: PSModule/Github-Script@v1
      id: paths
      env:
        GITHUB_ACTION_INPUT_TEST_PSMODULE_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_Settings: ${{ inputs.Settings }}
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        Script: ${{ github.action_path }}/scripts/main.ps1

    - name: Invoke-Pester
      uses: PSModule/Invoke-Pester@v3
      id: test
      env:
        LocalTestPath: ${{ fromJson(steps.paths.outputs.result).LocalTestPath }}
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        TestResult_TestSuiteName: ${{ inputs.Settings }}-${{ runner.os }}
        Path: ${{ fromJson(steps.paths.outputs.result).TestPath }}
        Run_Path: ${{ fromJson(steps.paths.outputs.result).CodePath }}
