name: 'Test-Module'
description: 'Test a PowerShell module before publishing the module to the PowerShell Gallery.'
branding:
  icon: activity
  color: blue

inputs:
  Path:
    description: 'Path to the module to publish.'
    required: true
  verbose:
    description: 'Enable verbose output.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run Test-Module
      shell: pwsh
      run: |
        Write-Output '::group::Test-Module'

        Write-Output '-------------------------------------------'
        Write-Output 'Action inputs:'
        $params = @{
            Message = '${{ inputs.message }}'
            Verbose = [System.Convert]::ToBoolean('${{ inputs.verbose }}')
        }
        $params.GetEnumerator() | Sort-Object -Property Name

        Write-Output '-------------------------------------------'

        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" @params

        Write-Output '::endgroup::'
