name: Test-PSModule
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
branding:
  icon: activity
  color: blue

inputs:
  Name:
    description: The name of the module to test.
    required: false
  Path:
    description: The path to the module to test.
    required: false
    default: outputs

runs:
  using: composite
  steps:
    - name: Run Test-PSModule
      shell: pwsh
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_Path: ${{ inputs.Path }}
      run: |
        # Test-PSModule
        Write-Host '::group::Loading libraries'
        Install-PSResource -Name 'Utilities', 'Pester', 'PSScriptAnalyzer' -TrustRepository -Verbose
        Write-Host '::endgroup::'

        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose
