name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Name:
    description: The name of the module to test. The name of the repository is used if not specified.
    required: false
  Path:
    description: The path to the code to test.
    required: true
  TestType:
    description: The type of tests to run. Can be either 'Module' or 'SourceCode'.
    required: true
  TestsPath:
    description: The path to the tests to run.
    required: false
    default: tests
  Shell:
    description: The shell to use for running the tests.
    required: false
    default: pwsh

outputs:
  passed:
    description: If the tests passed.
    value: ${{ steps.test.outputs.passed }}

runs:
  using: composite
  steps:
    - name: Run Test-PSModule
      id: test
      shell: ${{ inputs.Shell }}
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_TestType: ${{ inputs.TestType }}
        GITHUB_ACTION_INPUT_TestsPath: ${{ inputs.TestsPath }}
      run: |
        # Test-PSModule
        $IsUnix = $PSVersionTable.Platform -eq 'Unix'
        if ($IsUnix) {
            sudo pwsh "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
        } else {
            $passed = . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose
            "passed=$passed" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }
        if (-not $passed) {
            exit 1
        }

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ inputs.TestType == 'Module' && (success() || failure()) }}
      with:
        name: ${{ runner.os }}-${{ inputs.Shell }}-Test-Report
        path: ${{ github.workspace }}/outputs/Test-Report.xml

    - name: Upload code coverage report
      uses: actions/upload-artifact@v4
      if: ${{ inputs.TestType == 'Module' && (success() || failure()) }}
      with:
        name: ${{ runner.os }}-${{ inputs.Shell }}-CodeCoverage-Report
        path: ${{ github.workspace }}/outputs/CodeCoverage-Report.xml
