name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Name:
    description: The name of the module to test. The name of the repository is used if not specified.
    required: false
  Path:
    description: The path to the module to test.
    required: true
  RunModuleTests:
    description: Run the module tests.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Run Test-PSModule
      shell: pwsh
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_RunModuleTests: ${{ inputs.RunModuleTests }}
      run: |
        # Test-PSModule
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose
