name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Name:
    description: The name of the module to test. The name of the repository is used if not specified.
    required: false
  Path:
    description: The path to the repo.
    required: true
    default: ${{ github.workspace }}
  TestType:
    description: The type of tests to run. Can be either 'Module' or 'SourceCode'.
    required: true
  OS:
    description: The operating system to run the tests on.
    required: true

runs:
  using: composite
  steps:
    - name: Get test paths
      uses: PSModule/Github-Script@v1
      id: paths
      env:
        GITHUB_ACTION_INPUT_TEST_PSMODULE_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_TestType: ${{ inputs.TestType }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_OS: ${{ inputs.OS }}
      with:
        Script: ${{ github.action_path }}/scripts/main.ps1

    - name: Invoke-Pester
      uses: PSModule/Invoke-Pester@v3
      id: test
      with:
        TestResult_TestSuiteName: ${{ inputs.TestSuiteName}}
        Path: ${{ fromJson(steps.paths.outputs.result).TestPath }}
        Run_Path: ${{ fromJson(steps.paths.outputs.result).CodePath }}
