name: Test-PSModule
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
branding:
  icon: activity
  color: blue

inputs:
  Name:
    description: The name of the module to test.
    required: false
  Path:
    description: The path to the module to test.
    required: false
    default: outputs

runs:
  using: composite
  steps:
    - name: Run Test-PSModule
      shell: pwsh
      env:
        Name: ${{ inputs.Name }}
        Path: ${{ inputs.Path }}
      run: |
        Write-Host '::group::Loading libraries'
        $modules = 'Utilities', 'powershell-yaml'
        Install-PSResource -Name $modules -TrustRepository -Verbose
        Import-Module -Name $modules
        Write-Host '::endgroup::'

        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
