name: Test-PSModule (by PSModule)
description: Test a PowerShell module before publishing the module to the PowerShell Gallery.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

inputs:
  Name:
    description: The name of the module to test. The name of the repository is used if not specified.
    required: false
  Path:
    description: The path to the code to test.
    required: true
  TestType:
    description: The type of tests to run. Can be either 'Module' or 'SourceCode'.
    required: true
  OS:
    description: The operating system to run the tests on.
    required: true
  # Debug:
  #   description: Enable debug output.
  #   required: false
  #   default: 'false'
  # Verbose:
  #   description: Enable verbose output.
  #   required: false
  #   default: 'false'
  # Version:
  #   description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
  #   required: false
  # Prerelease:
  #   description: Allow prerelease versions if available.
  #   required: false
  #   default: 'false'

outputs:
  passed:
    description: If the tests passed.
    value: ${{ steps.test.outputs.Passed }}

runs:
  using: composite
  steps:
    - name: Get test paths
      uses: PSModule/Github-Script@v1
      id: paths
      env:
        GITHUB_ACTION_INPUT_TEST_PSMODULE_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_TestType: ${{ inputs.TestType }}
        GITHUB_ACTION_INPUT_TEST_PSMODULE_OS: ${{ inputs.OS }}
      with:
        Script: |
          # If test type is module, the code we ought to test is in the path/name folder, otherwise it's in the path folder.
          Write-Host "Test type: [$env:GITHUB_ACTION_INPUT_TEST_PSMODULE_TestType]"
          $codePath = switch($env:GITHUB_ACTION_INPUT_TEST_PSMODULE_TestType) {
            'Module' {
              Resolve-Path -Path "$env:GITHUB_ACTION_INPUT_TEST_PSMODULE_Path/$env:GITHUB_ACTION_INPUT_TEST_PSMODULE_Name" | Select-Object -ExpandProperty Path
            }
            'SourceCode' {
              Resolve-Path -Path $env:GITHUB_ACTION_INPUT_TEST_PSMODULE_Path | Select-Object -ExpandProperty Path
            }
            default {
              throw "Invalid test type: [$env:GITHUB_ACTION_INPUT_TEST_PSMODULE_TestType]"
            }
          }
          Write-Host "Path to code:  [$codePath]"
          Set-GitHubOutput -Name CodePath -Value $codePath

          $testPath = Resolve-Path -Path "${{ github.action_path }}/scripts/tests/${{ inputs.TestType }}" | Select-Object -ExpandProperty Path
          Write-Host "Path to tests: [$testPath]"
          Set-GitHubOutput -Name TestPath -Value $testPath

    - name: Invoke-Pester
      uses: PSModule/Invoke-Pester@fix
      id: test
      with:
        TestResult_TestSuiteName: ${{ inputs.OS }}-${{ inputs.TestType }}
        Path: ${{ fromJson(steps.paths.outputs.result).TestPath }}
        Run_Path: ${{ fromJson(steps.paths.outputs.result).CodePath }}
