name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

permissions: {}

jobs:
  ActionTest:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            shell: pwsh
            path: tests/src
            testtype: SourceCode
          - os: ubuntu-latest
            shell: pwsh
            path: tests/outputs/modules
            testtype: Module
          - os: macos-latest
            shell: pwsh
            path: tests/src
            testtype: sourcecode
          - os: macos-latest
            shell: pwsh
            path: tests/outputs/modules
            testtype: module
          - os: windows-latest
            shell: pwsh
            path: tests/src
            testtype: sourcecode
          - os: windows-latest
            shell: pwsh
            path: tests/outputs/modules
            testtype: module
          - os: windows-latest
            shell: powershell
            path: tests/src
            testtype: sourcecode
          - os: windows-latest
            shell: powershell
            path: tests/outputs/modules
            testtype: module
    name: Action-Test - [${{ matrix.os }}@${{ matrix.shell }}] - [${{ matrix.path }}]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main
        with:
          Shell: ${{ matrix.shell }}

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModuleTest
          Path: ${{ matrix.path }}
          Shell: ${{ matrix.shell }}
          TestType: ${{ matrix.TestType }}
