name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

jobs:
  ActionTestSrc:
    strategy:
      matrix:
        path: [tests\src, tests\outputs\modules]
    name: Action-Test - [${{ matrix.path }}]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout tests -> PSModuleTest
        uses: actions/checkout@v4
        with:
          repository: PSModule/PSModuleTest
          path: tests

      - name: Show files
        shell: pwsh
        run: |
          Get-ChildItem -Recurse | Select-Object -ExpandProperty FullName | Sort-Object

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModule
          Path: ${{ matrix.path }}
