name: Action-Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  ActionTestSrc:
    name: Action-Test - [src]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModuleTest
          Path: src

  ActionTestOutputs:
    name: Action-Test - [outputs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModuleTest
          Path: outputs/module
