name: Action-Test

on:
  push:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**
  pull_request_target:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**

jobs:
  ActionTestDefault:
    name: Action-Test - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModuleTest
          APIKey: ${{ secrets.APIKEY }}
