name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

permissions: {}

jobs:
  ActionTest:
    strategy:
      fail-fast: false
      matrix:
        shell: [pwsh]
        os: [ubuntu-latest, macos-latest, windows-latest]
        path: [tests/src, tests/outputs/modules]
        runModuleTests: [true]
        include:
          - shell: powershell
            os: windows-latest
            path: tests/src
          - shell: powershell
            os: windows-latest
            path: tests/outputs/modules
          - path: tests/src
            RunModuleTests: false
    name: Action-Test - [${{ matrix.os }}@${{ matrix.shell }}] - [${{ matrix.path }}]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main
        with:
          Shell: ${{ matrix.shell }}

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModuleTest
          Path: ${{ matrix.path }}
          Shell: ${{ matrix.shell }}
          RunModuleTests: ${{ matrix.RunModuleTests }}
