name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

jobs:
  ActionTestSrc:
    name: Action-Test - [src]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModule
          Path: src

  ActionTestOutputs:
    name: Action-Test - [outputs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModule
          Path: outputs/module
