name: Action-Test [Src-Default]

run-name: "Action-Test [Src-Default] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ActionTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Action-Test [Src-Default] - [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Action-Test
        uses: ./
        id: action-test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModuleTest
          Path: tests/src
          TestType: SourceCode

      - name: Status
        shell: pwsh
        run: |
          $passed = '${{ steps.action-test.outputs.passed }}'
          Write-Host "Passed: [$Passed]"
          if ($passed -eq 'False') {
            exit 1
          }
